### ISSUE TITLE
Solidity Compilation Error on Importing BLSApkRegistry: Base Must Precede Derived Contract

### ISSUE THREAD

**Issue by ny-alt** [Layr-Labs/eigenlayer-middleware#103] opened 2023-12-13 14:59 UTC
**Describe the bug**

An error occurs during the compilation of [Sample.sol](https://github.com/ny-alt/sample-fe3ae2/blob/master/src/Sample.sol), specifically after importing BLSApkRegistry.

Sample.sol
```
// SPDX-License-Identifier: UNLICENSED
pragma solidity =0.8.12;

import {BLSApkRegistry} from "eigenlayer-middleware/src/BLSApkRegistry.sol";
``` 

Compilation Error
```
Compiler run failed:
Error (2449): Definition of base has to precede definition of derived contract
  --> src/interfaces/IStakeRegistry.sol:13:29:
   |
13 | interface IStakeRegistry is IRegistry {
   |                             ^^^^^^^^^
```

Detailed error logs and context can be found in the GitHub Actions workflow at [this link](https://github.com/ny-alt/sample-fe3ae2/actions/runs/7196849650/job/19602614913).

**To Reproduce**
1. git clone https://github.com/ny-alt/sample-fe3ae2.git
2. forge compile

**Expected behavior**
The expected behavior is that the Solidity project should compile without errors.

**Comment by ChaoticWalrus** [comment] 2023-12-13 17:05
I experienced this error recently, and am trying to sort out the root cause, because it appeared while making unrelated changes.

@ny-alt a workaround for you, that has worked for me repeatedly:

1. run `forge clean`
2. immediately followed by whatever other command you're trying to run (`forge b`, `forge t`, etc.)

Obviously this isn't ideal, but let me know if it doesn't fix the problem for you

**Comment by ChaoticWalrus** [comment] 2023-12-13 22:44
This should have been fixed in https://github.com/Layr-Labs/eigenlayer-middleware/pull/108
Please reopen this issue if that PR doesn't sort things out for you.

**Closed by ChaoticWalrus** 2023-12-13 22:44 UTC
